version: '2'

services:
  dev:
    image: portal-build
    build:
      context: .
      args:
        BUILDER_UID: 1000
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - './:/app'
      - '$HOME/.m2:/home/builder/.m2'
      - '${HOME}/.grails:/home/builder/.grails'
  debug:
    build: Dockerfile.dev
    volumes:
      - ~/.m2:/root/.m2
      - ~/.grails:/root/.grails
      - ./:/app
    entrypoint: grails
    command: run-app --debug-fork
    ports:
      - "8080:8080" #Grails default port
      - "5005:5005" #Grails debug port
      
