name: Docker Build Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker Image
        uses: docker/build-push-action@v4
        env:
          BUILDER_UID: ${{ runner.uid }}
        with:
          context: .
          file: Dockerfile.build
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: aodn-portal-build

      - name: Run Pipeline Steps
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -v ${{ runner.home }}/bin:${HOME}/bin \
            -w /workspace \
            --entrypoint /bin/bash \
            aodn-portal-build -c '
            mvn -B clean test
            grails -DARTIFACT_BUILD_NUMBER=${BUILD_NUMBER} -Dgrails.work.dir=${WORKSPACE}/target clean --non-interactive --plain-output
            grails -DARTIFACT_BUILD_NUMBER=${BUILD_NUMBER} -Dgrails.work.dir=${WORKSPACE}/target war --non-interactive --plain-output
          '

      - name: Archive Artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v3
        with:
          name: war-file
          path: target/*.war
